In [2]:
from TransformingCity import TransformingCity, LandUseViewer, PopulationViewer

import numpy as np
import matplotlib.pyplot as plt

from matplotlib import rc
rc('animation', html='html5')

In [3]:
city = TransformingCity(10)
city.array = city.landuse # default array is landuse
viewer = LandUseViewer(city)
anim = viewer.animate()

In [4]:
anim

In [5]:
print(city.array)

[[1 1 2 1 1 1 1 2 1 6]
 [1 5 1 1 1 1 2 1 1 2]
 [1 1 1 1 6 3 1 1 6 1]
 [3 3 5 1 1 2 1 2 5 1]
 [1 1 1 1 6 1 5 5 3 1]
 [1 6 6 5 5 1 1 1 3 6]
 [1 1 3 1 1 1 1 6 1 6]
 [5 1 1 2 1 6 1 1 1 3]
 [1 1 1 1 5 1 1 1 1 3]
 [1 2 1 2 1 3 6 1 1 2]]


In [6]:
city = TransformingCity(10)
city.array = city.occupants # default array is landuse
viewer = PopulationViewer(city)
anim = viewer.animate()

AttributeError: 'collections.defaultdict' object has no attribute 'shape'