In [1]:
from TransformingCity import TransformingCity, LandUseViewer, PopulationViewer

import numpy as np
import matplotlib.pyplot as plt

from matplotlib import rc
rc('animation', html='html5')

AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'

In [2]:
city = TransformingCity(10)
city.array = city.landuse # default array is landuse
viewer = LandUseViewer(city)
anim = viewer.animate()

NameError: name 'TransformingCity' is not defined

In [15]:
anim

In [16]:
print(city.array)

[[1 3 3 1 1 1 1 1 1 2]
 [1 3 3 3 2 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 5 1]
 [1 2 3 2 2 1 3 1 3 1]
 [1 3 3 1 3 5 2 1 1 3]
 [1 5 3 1 3 3 1 1 2 5]
 [1 1 1 1 1 1 1 2 1 3]
 [1 1 3 3 2 6 1 1 1 6]
 [1 5 1 1 1 1 6 5 5 1]
 [1 5 2 1 6 1 3 5 6 3]]


In [18]:
city = TransformingCity(10)
city.step()
city.array = city.pop_count_cr # default array is landuse
print(city.pop_count_cr)
viewer = PopulationViewer(city)
anim = viewer.animate()

AttributeError: 'TransformingCity' object has no attribute 'pop_count_cr'

In [10]:
anim