In [1]:
from TransformingCity import TransformingCity, LandUseViewer

import numpy as np
import matplotlib.pyplot as plt

from matplotlib import rc
rc('animation', html='html5')

In [2]:
city = TransformingCity(10)
city.array = city.landuse # default array is landuse
viewer = LandUseViewer(city)
anim = viewer.animate()

In [3]:
anim

In [4]:
print(city.array)

[[1 2 1 2 1 5 1 5 1 3]
 [1 6 1 1 6 1 6 1 1 1]
 [2 6 3 1 1 5 3 1 1 1]
 [1 1 1 5 5 2 2 2 6 5]
 [1 2 1 1 1 2 1 1 1 1]
 [5 1 1 1 1 1 1 3 2 1]
 [6 6 2 1 6 1 1 1 1 3]
 [1 1 3 2 2 2 2 5 1 5]
 [1 5 3 6 5 5 2 1 1 1]
 [1 1 1 1 1 1 1 1 3 3]]
